Add script for updating Reaper packages
Cloud-Scythe-Labs/reascript-rs pull request #20
Opened 2024-09-03 23:09 UTC by andrewvious

Closes #19 

Adds `update_reaper_flake_input.sh` which updates the Reaper packages to the **most** recent version and runs a check in CI that opens a pull request that will update the Reaper input to the flake.

2024-09-07 15:43 UTC, andrewvious commented
Ready for review @eureka-cpu

2024-09-07 15:46 UTC, eureka-cpu requested changes
Looking good, nice work!

2024-09-07 15:46 UTC, eureka-cpu commented on .github/workflows/generate_reaper_plugin_functions.yml
> +      - name: Check if rs update is needed
this name could be more descriptive

2024-09-07 15:46 UTC, eureka-cpu commented on lib/update.nix
> +{ pkgs, ... }:
Not strictly necessary, but you could replace `pkgs` with the specific things you need from it (have a look at nix-watch.nix for an example)

2024-09-08 01:45 UTC, eureka-cpu requested changes
Just need to change `lib/update.nix` to `scripts/update-reaper-flake-input.nix`

2024-09-08 14:03 UTC, eureka-cpu approved these changes

2024-09-08 14:31 UTC, merged